server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: ${IDENTITY_ORIGIN}
          predicates:
            - Path=/identity/**
          filters:
            - StripPrefix=1
        - id: file_service
          uri: ${FILE_ORIGIN}
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
        - id: email_service
          uri: ${EMAIL_ORIGIN}
          predicates:
            - Path=/email/**
          filters:
            - StripPrefix=1
        - id: profile_service
          uri: ${PROFILE_ORIGIN}
          predicates:
            - Path=/profile/**
          filters:
            - StripPrefix=1
        - id: relationship_service
          uri: ${RELATIONSHIP_ORIGIN}
          predicates:
            - Path=/relationship/**
          filters:
            - StripPrefix=1
        - id: post_service
          uri: ${POST_ORIGIN}
          predicates:
            - Path=/post/**
          filters:
            - StripPrefix=1

client:
  identity: ${IDENTITY_ORIGIN}
fe-origin: ${FRONT_END}
