spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8084
client:
  file: ${FILE_ORIGIN}
  relationship: ${RELATIONSHIP_ORIGIN}
